# fly.toml app configuration file generated for nodechat on 2023-11-06T14:15:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nodechat"
primary_region = "iad"

[build]

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
